name: jsonplaceholder_client
description: A jsonplaceholder client for Dart.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  dio: ^3.0.9
  fresh:
    path: ../../../
  json_annotation: ^3.0.1
  meta: ^1.1.8

dev_dependencies:
  json_serializable: ^3.3.0
  build_runner: ^1.9.0
