name: user_repository
description: A User Dart Repository
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  jsonplaceholder_client:
    path: ../jsonplaceholder_client
