name: Flutter Package Workflow
description: Build and test a Flutter package.

inputs:
  concurrency:
    required: false
    default: "4"
    description: The value of the concurrency flag (-j) used when running tests
  coverage_excludes:
    required: false
    default: ""
    description: Globs to exclude from coverage
  working_directory:
    required: false
    default: "."
    description: The working directory for this workflow
  min_coverage:
    required: false
    default: "100"
    description: The minimum coverage percentage value
  analyze_directories:
    required: false
    default: "lib test"
    description: Directories to analyze
  report_on:
    required: false
    default: "lib"
    description: Directories to report on when collecting coverage
  platform:
    required: false
    default: "vm"
    description: Platform to use when running tests

runs:
  using: "composite"
  steps:
    - name: 🐦 Setup Flutter
      uses: subosito/flutter-action@v2

    - name: 📦 Install Dependencies
      working-directory: ${{ inputs.working_directory }}
      shell: ${{ inputs.shell }}
      run: flutter pub get

    - name: ✨ Format
      working-directory: ${{ inputs.working_directory }}
      shell: ${{ inputs.shell }}
      run: dart format --set-exit-if-changed .

    - name: 🔍 Analyze
      working-directory: ${{ inputs.working_directory }}
      shell: ${{ inputs.shell }}
      run: dart analyze --fatal-warnings ${{inputs.analyze_directories}}

    - name: 🧪 Test
      working-directory: ${{ inputs.working_directory }}
      shell: ${{ inputs.shell }}
      run: |
        if [ -d "test" ]; then
          flutter test --no-pub --test-randomize-ordering-seed random --coverage
        fi

    - name: 📊 Verify Coverage
      if: inputs.collect_coverage == 'true'
      uses: VeryGoodOpenSource/very_good_coverage@v3
      with:
        path: ${{inputs.working_directory}}/coverage/lcov.info
        exclude: ${{inputs.coverage_excludes}}
        min_coverage: ${{inputs.min_coverage}}

    - name: 💯 Verify Pub Score
      if: inputs.collect_score == 'true'
      working-directory: ${{ inputs.working_directory }}
      shell: ${{ inputs.shell }}
      run: |
        dart pub global activate pana 0.21.45
        sudo apt-get install webp
        PANA=$(pana . --no-warning); PANA_SCORE=$(echo $PANA | sed -n "s/.*Points: \([0-9]*\)\/\([0-9]*\)./\1\/\2/p")
        echo "score: $PANA_SCORE"
        IFS='/'; read -a SCORE_ARR <<< "$PANA_SCORE"; SCORE=SCORE_ARR[0]; TOTAL=SCORE_ARR[1]
        if [ -z "$1" ]; then MINIMUM_SCORE=TOTAL; else MINIMUM_SCORE=$1; fi
        if (( $SCORE < $MINIMUM_SCORE )); then echo "minimum score $MINIMUM_SCORE was not met!"; exit 1; fi
