name: ci

on:
  pull_request:
    paths:
      - "!packages/fresh_dio/lib/**"
      - "!packages/fresh_dio/test/**"
      - "!packages/fresh_dio/example/**"
      - "!packages/fresh/lib/**"
      - "!packages/fresh/test/**"
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: noop
        run: echo 'noop'
