name: example

on:
  push:
    branches:
      - master
    paths:
      - "example/**"
  pull_request:
    branches:
      - master
    paths:
      - "example/**"

jobs:
  example:
    defaults:
      run:
        working-directory: example
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.3.0
      - name: Install Dependencies
        run: flutter packages get
      - name: Format
        run: flutter format --set-exit-if-changed lib
      - name: Analyze
        run: flutter analyze lib
      - name: Run tests
        run: flutter test --no-pub --coverage --test-randomize-ordering-seed random
